name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip list
      
      - name: Run tests
        run: |
          pytest tests/ --import-mode=importlib
      
      - name: Check PEP8
        run: flake8 app/
