name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip list  # Для отладки
      - name: Run tests
        run: pytest tests/
      - name: Check PEP8
        run: flake8 app/
