name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.21.6
          pip install torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
      - name: Run flake8
        run: |
          flake8 app/ tests/ --max-line-length=120
      - name: Run tests
        run: |
          python -c "import torch; print(f'Torch config: {torch.__config__.show()}')"
          pytest tests/ -v
